package org.example.gui.panel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import org.example.bus.CTHoaDonBUS;
import org.example.dto.CTietHDDTO;
import org.example.gui.dialog.CTHoaDonDialog;
import org.example.gui.helper.ExcelHelper;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/** @author Nhat */
public class CTHoaDonPanel extends JPanel {
    // define valuables
    private JButton btnreset, btnThem, btnTim, btnxoa, btnxuat;
    private JComboBox<String> cbTim;
    private JPanel jPanel1, jPanel2, jPanel3;
    private JScrollPane jScroll;
    private JTable tblCthd;
    private JLabel txtName;
    private JTextField txtTim;

    private DefaultTableModel model;
    private CTHoaDonBUS bus;
    private int soLuongCanXoa = 0;

    public CTHoaDonPanel() {
        initComponents();
        bus = new CTHoaDonBUS();
        bus.docDs();
        model = (DefaultTableModel) tblCthd.getModel();
        tblCthd.isCellEditable(ERROR, WIDTH);
        loadData();
    }

    public CTHoaDonPanel(String mahd) {
        initComponents();
        bus=new CTHoaDonBUS();
        txtName.setText("Chi tiết hóa đơn: "+mahd);
        model=(DefaultTableModel) tblCthd.getModel();
        txtTim.setVisible(false);
        btnTim.setVisible(false);
        cbTim.setVisible(false);
        btnThem.setVisible(false);
        btnxoa.setVisible(false);
        btnxuat.setVisible(false);
        btnreset.setVisible(false);
        loadChiTiet(mahd);
    }

    public CTHoaDonPanel(String maHD,int veDu) {
        initComponents();
        bus = new CTHoaDonBUS();
        txtName.setText("Chi tiết hóa đơn: "+maHD);
        model=(DefaultTableModel) tblCthd.getModel();
        txtTim.setVisible(false);
        btnTim.setVisible(false);
        cbTim.setVisible(false);
        btnThem.setVisible(false);
        btnxoa.setVisible(false);
        btnxuat.setVisible(false);

        if(veDu>0){
            this.soLuongCanXoa=veDu;
            btnxoa.setVisible(true);
            txtName.setText("Cần xóa thêm "+veDu+" VÉ");
        }else{
            btnxoa.setVisible(true);
        }
        loadChiTiet(maHD);
    }

    private void loadData(){
        model.setRowCount(0);
        DefaultTableModel model=(DefaultTableModel) tblCthd.getModel();
        ArrayList<CTietHDDTO> ds= CTHoaDonBUS.getDs();
        for(CTietHDDTO cthd:ds){
            model.addRow(new Object[]{
                    cthd.getMaHD(),cthd.getMaKHDi(),String.format("%.0f", cthd.getGiaVe())
            });
        }
    }

    private void loadData(ArrayList<CTietHDDTO> ds){
        model.setRowCount(0);
        String loai =cbTim.getSelectedItem().toString();
        String key=txtTim.getText().toString().trim();
        ds= bus.timNangcao(loai, key);
        for(CTietHDDTO cthd:ds){
            model.addRow(new Object[]{
                    cthd.getMaHD(),cthd.getMaKHDi(),cthd.getGiaVe()
            });
        }
    }

    private void loadChiTiet(String mahd){
        DefaultTableModel model=(DefaultTableModel) tblCthd.getModel();
        this.model.setRowCount(0);

        try{
            CTHoaDonBUS bus=new CTHoaDonBUS();
            ArrayList<CTietHDDTO> ds=bus.getDstheoma(mahd);
            if(ds!=null){
                for(CTietHDDTO cthd:ds){
                    model.addRow(new Object[]{
                            cthd.getMaHD(),cthd.getMaKHDi(),cthd.getGiaVe()
                    });
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Loi");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbTim = new javax.swing.JComboBox<>();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jScroll = new javax.swing.JScrollPane();
        tblCthd = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnxuat = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        txtName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName.setText("Quản lý Chi tiết hóa đơn");
        jPanel1.add(txtName, java.awt.BorderLayout.CENTER);

        cbTim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hóa đơn", "Mã khách hàng" }));
        jPanel2.add(cbTim);

        txtTim.setColumns(20);
        jPanel2.add(txtTim);

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        jPanel2.add(btnTim);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblCthd.setModel(new DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "Mã hóa đơn", "Mã khách hàng", "Giá vé"
                }
        ));
        jScroll.setViewportView(tblCthd);

        add(jScroll, java.awt.BorderLayout.CENTER);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTHoaDonDialog cthd=new CTHoaDonDialog();
                cthd.setModal(true);
                cthd.setVisible(true);
                loadData();
            }
        });
        jPanel3.add(btnThem);

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnxoa);

        btnreset.setText("Làm mới");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel3.add(btnreset);

        btnxuat.setText("Xuất excel");
        btnxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatActionPerformed(evt);
            }
        });
        jPanel3.add(btnxuat);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

//    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
//        // TODO add your handling code here:
//        CTHoaDonDialog cthd=new CTHoaDonDialog();
//        cthd.setModal(true);
//        cthd.setVisible(true);
//        loadData();
//    }//GEN-LAST:event_btnThemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int row=tblCthd.getSelectedRow();

        if(row==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn chi tiết cần xóa");
            return;
        }

        String maHD =model.getValueAt(row, 0).toString();
        String maKh =model.getValueAt(row, 1).toString();

        if(JOptionPane.showConfirmDialog(this, "Xóa vé này?","Xác nhận",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            if(bus.xoaCtietHd(maHD,maKh)){
                model.removeRow(row);
                JOptionPane.showMessageDialog(this, "Xóa thành công");

                if(soLuongCanXoa>0){
                    soLuongCanXoa--;
                    if(soLuongCanXoa>0){
                        txtName.setText("Cần xóa thêm "+soLuongCanXoa+" VÉ");

                    }else{
                        txtName.setText("Đã xóa đủ");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String tim =txtTim.getText().toString().trim();

        String loai = cbTim.getSelectedItem().toString();

        if(tim.isEmpty()){
            model.setRowCount(0);
            return;
        }else {
            loadData(bus.timNangcao(loai, tim));
        }

    }//GEN-LAST:event_btnTimActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatActionPerformed
        // TODO add your handling code here:
        ExcelHelper.xuatExcel(tblCthd, this, "Danh sách chi tiết hóa đơn");
    }//GEN-LAST:event_btnxuatActionPerformed
}
