/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.example.gui.dialog;

import java.util.ArrayList;
import org.example.bus.CTHoaDonBUS;
import org.example.bus.KhachHangBUS;
import org.example.dto.KhachHang;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.example.dto.CTietHDDTO;

/**
 *
 * @author Nhat
 */
public class NhapCTHD extends javax.swing.JDialog {
    private String mahd;
    private int soluong;
    private CTHoaDonBUS bus;
    /**
     * Creates new form NhapCTHD
     */
    public NhapCTHD(java.awt.Frame parent, boolean modal,String mahd,int soluong) {
        super(parent, modal);
        this.soluong=soluong;
        this.mahd=mahd;
        bus=new org.example.bus.CTHoaDonBUS();
        this.setTitle("Nhập chi tiết hóa đơn");
        this.setLocationRelativeTo(null);
        initComponents();
        loaddata();
        setupComboBoxKhachHang();
    }
    
    public NhapCTHD(String ma) {
        this.soluong=soluong;
        this.mahd=mahd;
        bus=new org.example.bus.CTHoaDonBUS();
        this.setTitle("Chi tiết hóa đơn của hóa đơn: "+ma);
        this.setLocationRelativeTo(null);
        initComponents();
        btnluu.setVisible(false);
        tblnhapct.setDefaultEditor(Object.class, null);
        loaddata(ma);
        
    }
    private void setupComboBoxKhachHang() {
    JComboBox<String> cbKhachHang = new JComboBox<>();
    
    KhachHangBUS khBus = new KhachHangBUS();
    if (KhachHangBUS.dsKH == null) {
        khBus.docDSKH();
    }
    
    for (KhachHang kh : KhachHangBUS.dsKH) {
        cbKhachHang.addItem(kh.getMaKH());
    }
    
    TableColumn khColumn = tblnhapct.getColumnModel().getColumn(1);
    khColumn.setCellEditor(new DefaultCellEditor(cbKhachHang));
    }

    private void loaddata(){
        DefaultTableModel model=(DefaultTableModel) tblnhapct.getModel();
        
        model.setRowCount(0);
        
        for(int i=0;i<soluong;i++){
            model.addRow(new Object[]{mahd,"",bus.laygia(mahd)});
        }
    }
    private void loaddata(String mahd){
        DefaultTableModel model=(DefaultTableModel) tblnhapct.getModel();
        
        model.setRowCount(0);
        
        ArrayList<CTietHDDTO> ds=bus.getDstheoma(mahd);
        for(CTietHDDTO cthddto: ds){
            model.addRow(new Object[]{
                cthddto.getMaHD(),cthddto.getMaKHDi(),cthddto.getGiaVe()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblnhapct = new javax.swing.JTable();
        btnluu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblnhapct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã khách hàng", "Giá vé"
            }
        ));
        tblnhapct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblnhapctKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblnhapct);

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnluu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model=(DefaultTableModel) tblnhapct.getModel();
        
        if(tblnhapct.isEditing()){
            tblnhapct.getCellEditor().stopCellEditing();
        }
        
        boolean loi=false;
        for(int i=0;i<soluong;i++){
            String mahd =model.getValueAt(i, 0).toString().trim();
            String makh =model.getValueAt(i, 1).toString().trim();
            float giave= Float.parseFloat(model.getValueAt(i, 2).toString().trim());
            org.example.dto.CTietHDDTO cthd=new org.example.dto.CTietHDDTO(mahd,makh,giave);
            if(!bus.themCTietHd(cthd)){
                loi=true;
                break;
        }
    }//GEN-LAST:event_btnluuActionPerformed
        if(!loi){
        JOptionPane.showMessageDialog(this, "Lưu thành công");
        this.dispose();
    }else{
        JOptionPane.showMessageDialog(this, "Lỗi");
    }
    }    
    private void tblnhapctKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblnhapctKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblnhapctKeyPressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnluu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblnhapct;
    // End of variables declaration//GEN-END:variables
}
